languageCode = "en-us"
title = "Sherly's Snippets"
baseURL = "https://xsher.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Sherly's random snippets, built with **Cupper**.\n\n"
